package com.example.simon.ingegneriauniparthenope;

import java.util.ArrayList;

public class ListaDocenti {
    static public ArrayList<String> nome=new ArrayList<String>();
    static public ArrayList<String> telefono=new ArrayList<String>();
    static public ArrayList<String> studio=new ArrayList<String>();
    static public ArrayList<String> email=new ArrayList<String>();

    public ListaDocenti(){
        this.addNomi();
        this.addTelefoni();
        this.addStudi();
        this.addEmail();

    }

    private void addTelefoni() {
        telefono.add("081-5476769");
        telefono.add("081-5476719");
        telefono.add("081-5476730");
        telefono.add("081-5476769");
        telefono.add("081-5476590");
        telefono.add("081-5476721");
        telefono.add("081-5476757");
        telefono.add("081-5476725");
        telefono.add("081-5476717");
        telefono.add("081-5476739");
        telefono.add("081-5476786");
        telefono.add("081-5476728");
        telefono.add("081-5476733");
        telefono.add("081-5476732/6714");
        telefono.add("081-5476727");
        telefono.add("081-5476745");
        telefono.add("081-5476702");
        telefono.add("081-5476723");
        telefono.add("081-5476766");
        telefono.add("081-5476767");
        telefono.add("081-5476741");
        telefono.add("081-5476759");
        telefono.add("081-5476731");
        telefono.add("081-5476716");
        telefono.add("NO");
        telefono.add("081-5476748");
        telefono.add("081-5476713");
        telefono.add("081-5476769");
        telefono.add("081-5476706");
        telefono.add("NO");
        telefono.add("081-5476718");
        telefono.add("081-5476762");
        telefono.add("NO");
        telefono.add("081-5476582");
        telefono.add("081-5476726");
        telefono.add("081-5476729");
        telefono.add("081-5476735");
        telefono.add("081-5476705");
        telefono.add("081-5476792");
        telefono.add("081-5476715");
        telefono.add("081-5476779");
        telefono.add("081-5476733");
        telefono.add("081-5476793");
        telefono.add("081-5476712");
        telefono.add("081-5476785");
        telefono.add("081-5476703");
        telefono.add("081-5476747");
        telefono.add("081-5476734");
        telefono.add("081-5476532");
        telefono.add("NO");
        telefono.add("081-5476700");
        telefono.add("081-5476745");
        telefono.add("081-5476781");
        telefono.add("081-5476749");
        telefono.add("081-5476755");
        telefono.add("081-5476744");
        telefono.add("081-5476764");
        telefono.add("081-5476791");
        telefono.add("081-5476720");
        telefono.add("081-5476752");
        telefono.add("081-5476724");
    }

    private void addNomi() {
        nome.add("Ambrosino Roberto");
        nome.add("Ariola Marco");
        nome.add("Aversa Stefano");
        nome.add("Baselice Fabio");
        nome.add("Benassai Guido");
        nome.add("Betta M. Francesca");
        nome.add("Bracale Antonio");
        nome.add("Budillon Alessandra");
        nome.add("Campopiano Stefania");
        nome.add("Caramia Pierluigi");
        nome.add("Carotenuto Alberto");
        nome.add("Caterino Nicola");
        nome.add("Ceroni Francesca");
        nome.add("Cioffi Raffaele");
        nome.add("Colangelo Francesco");
        nome.add("Conventi Francesco");
        nome.add("Coppolino Luigi");
        nome.add("Cozzolino Luca");
        nome.add("D'Antonio Salvatore");
        nome.add("D'Aquino Massimiliano");
        nome.add("Darsena Donatella");
        nome.add("De Sanctis Luca");
        nome.add("Della Morte Renata");
        nome.add("Di Gennaro Roberta");
        nome.add("Facci Andrea");
        nome.add("Feo Filomena");
        nome.add("Ferone Claudio");
        nome.add("Ferraioli Giampaolo");
        nome.add("Ferrara Giuseppe");
        nome.add("Forcina Antonio");
        nome.add("Iadicicco Agostino");
        nome.add("Jannelli Elio");
        nome.add("Labate Carmelo Vincenzo");
        nome.add("Lega Massimiliano");
        nome.add("Maglioccola Francesco");
        nome.add("Maiorano Rossella");
        nome.add("Massarotti Nicola");
        nome.add("Migliaccio Maurizio");
        nome.add("Minutillo Mariagiovanna");
        nome.add("Napolitano Antonio");
        nome.add("Nunziata Ferdinando");
        nome.add("Occhiuzzi Antonio");
        nome.add("Paderni Gabriella");
        nome.add("Pascazio Vito");
        nome.add("Passaro Renato");
        nome.add("Perna Stefano");
        nome.add("Petrillo Antonella");
        nome.add("Pugliano Giovanni");
        nome.add("Pugliano Giuseppina");
        nome.add("Robustelli Umberto");
        nome.add("Romano Luigi");
        nome.add("Rossi Elvira");
        nome.add("Roviello Giuseppina");
        nome.add("Schirinzi Gilda");
        nome.add("Sorrentino Francesco");
        nome.add("Tancredi Urbano");
        nome.add("Thomas Antonio");
        nome.add("Vadursi Michele");
        nome.add("Valoroso Nunziante");
        nome.add("Vanoli Laura");
        nome.add("Volzone Bruno");
    }

    private void addStudi() {
        studio.add("VI Piano - Lato Nord - Stanza 618");
        studio.add("V Piano - Lato Sud - Stanza 501");
        studio.add("VI Piano - Lato Sud - Stanza 601");
        studio.add("V Piano - Lato Sud - Stanza 510");
        studio.add("IV Piano - Lato Sud - Stanza 405");
        studio.add("VI Piano - Lato Nord - Stanza 615");
        studio.add("VI Piano - Lato Nord - Stanza 620");
        studio.add("V Piano - Lato Sud - Stanza 504");
        studio.add("V Piano - Lato Sud - Stanza 502");
        studio.add("VI Piano - Lato Nord - Stanza 620");
        studio.add("VI Piano - Lato Sud - Stanza 608");
        studio.add("VI Piano - Lato Sud - Stanza 614");
        studio.add("VI Piano - Lato Sud - Stanza 604");
        studio.add("VI Piano - Lato Sud - Stanza 603");
        studio.add("VI Piano - Lato Nord - Stanza 629");
        studio.add("V Piano - Lato Sud - Stanza 517");
        studio.add("V Piano - Lato Sud - Stanza 512");
        studio.add("VI Piano - Lato Sud - Stanza 613");
        studio.add("V Piano - Lato Sud - Stanza 511");
        studio.add("V Piano - Lato Sud - Stanza 507/E");
        studio.add("V Piano - Lato Sud - Stanza 504");
        studio.add("VI Piano - Lato Sud - Stanza 614");
        studio.add("VI Piano - Lato Sud - Stanza 602");
        studio.add("VI Piano - Lato Nord - Stanza 619");
        studio.add("VI Piano - Lato Nord - Stanza 628");
        studio.add("VI Piano - Lato Nord - Stanza 619");
        studio.add("VI Piano - Lato Sud - Stanza 612");
        studio.add("V Piano - Lato Sud - Stanza 510");
        studio.add("V Piano - Lato Sud - Stanza 509\t");
        studio.add("VI Piano - Lato Nord - Stanza 629");
        studio.add("V Piano - Lato Sud - Stanza 502");
        studio.add("VI Piano - Lato Sud - Stanza 609");
        studio.add("VI Piano - Lato Nord - Stanza 618");
        studio.add("VI Piano - Lato Nord - Stanza 617");
        studio.add("VI Piano - Lato Nord - Stanza 617");
        studio.add("VI Piano - Lato Sud - Stanza 613");
        studio.add("VI Piano - Lato Sud - Stanza 606");
        studio.add("V Piano - Lato Sud - Stanza 508");
        studio.add("VI Piano - Lato Nord - Stanza 628");
        studio.add("V Piano - Lato Sud - Stanza 505");
        studio.add("V Piano - Lato Sud - Stanza 507/W");
        studio.add("VI Piano - Lato Sud - Stanza 604");
        studio.add("VI Piano - Lato Nord - Stanza 615");
        studio.add("VI Piano - Lato Sud - Stanza 610/B");
        studio.add("V Piano - Lato Sud - Stanza 506");
        studio.add("V Piano - Lato Sud - Stanza 512");
        studio.add("VI Piano - Lato Nord - Stanza 629");
        studio.add("VI Piano - Lato Sud - Stanza 605");
        studio.add("IV Piano - Lato Nord - Stanza 424");
        studio.add("VI Piano - Lato Sud - Stanza 605");
        studio.add("V Piano - Lato Sud - Stanza 513");
        studio.add("V Piano - Lato Sud - Stanza 517");
        studio.add("VI Piano - Lato Sud - Stanza 612");
        studio.add("V Piano - Lato Sud - Stanza 503");
        studio.add("V Piano - Lato Sud - Stanza 517");
        studio.add("V Piano - Lato Sud - Stanza 511");
        studio.add("V Piano - Lato Sud - Stanza 507/W\t");
        studio.add("V Piano - Lato Sud - Stanza 507/E");
        studio.add("VI Piano - Lato Nord - Stanza 616");
        studio.add("VI Piano - Lato Sud - Stanza 606");
        studio.add("VI Piano - Lato Nord - Stanza 616");
    }

    private void addEmail() {
        email.add("roberto.ambrosino@uniparthenope.it");
        email.add("marco.ariola@uniparthenope.it");
        email.add("stefano.aversa@uniparthenope.it");
        email.add("fabio.baselice@uniparthenope.it");
        email.add("guido.benassai@uniparthenope.it");
        email.add("francesca.betta@uniparthenope.it");
        email.add("antonio.bracale@uniparthenope.it");
        email.add("alessandra.budillon@uniparthenope.it");
        email.add("stefania.campopiano@uniparthenope.it");
        email.add("pierluigi.caramia@uniparthenope.it");
        email.add("alberto.carotenuto@uniparthenope.it");
        email.add("nicola.caterino@uniparthenope.it");
        email.add("francesca.ceroni@uniparthenope.it");
        email.add("raffaele.cioffi@uniparthenope.it");
        email.add("francesco.colangelo@uniparthenope.it");
        email.add("francesco.conventi@uniparthenope.it");
        email.add("luigi.coppolino@uniparthenope.it");
        email.add("luca.cozzolino@uniparthenope.it");
        email.add("salvatore.dantonio@uniparthenope.it");
        email.add("massimiliano.daquino@uniparthenope.it");
        email.add("donatella.darsena@uniparthenope.it");
        email.add("luca.desanctis@uniparthenope.it");
        email.add("renata.dellamorte@uniparthenope.it");
        email.add("roberta.digennaro@uniparthenope.it");
        email.add("andrea.facci@uniparthenope.it");
        email.add("filomena.feo@uniparthenope.it");
        email.add("claudio.ferone@uniparthenope.it");
        email.add("giampaolo.ferraioli@uniparthenope.it");
        email.add("giuseppe.ferrara@uniparthenope.it");
        email.add("antonio.forcina@uniparthenope.it");
        email.add("agostino.iadicicco@uniparthenope.it");
        email.add("elio.jannelli@uniparthenope.it");
        email.add("carmelenzo.labate@uniparthenope.it");
        email.add("lega@uniparthenope.it");
        email.add("francesco.maglioccola@uniparthenope.it");
        email.add("rossella.maiorano@uniparthenope.it");
        email.add("nicola.massarotti@uniparthenope.it");
        email.add("maurizio.migliaccio@uniparthenope.it");
        email.add("mariagiovanna.minutillo@uniparthenope.it");
        email.add("antonio.napolitano@uniparthenope.it");
        email.add("ferdinando.nunziata@uniparthenope.it");
        email.add("antonio.occhiuzzi@uniparthenope.it");
        email.add("gabriella.paderni@uniparthenope.it");
        email.add("vito.pascazio@uniparthenope.it");
        email.add("renato.passaro@uniparthenope.it");
        email.add("stefano.perna@uniparthenope.it");
        email.add("antonella.petrillo@uniparthenope.it");
        email.add("giovanni.pugliano@uniparthenope.it");
        email.add("giuseppina.pugliano@uniparthenope.it");
        email.add("umberto.robustelli@uniparthenope.it");
        email.add("luigi.romano@uniparthenope.it");
        email.add("elvira.rossi@uniparthenope.it");
        email.add("giuseppina.roviello@uniparthenope.it");
        email.add("gilda.schirinzi@uniparthenope.it");
        email.add("francesco.sorrentino@uniparthenope.it");
        email.add("urbano.tancredi@uniparthenope.it");
        email.add("antonio.thomas@uniparthenope.it");
        email.add("vadursi@uniparthenope.it");
        email.add("nunziante.valoroso@uniparthenope.it");
        email.add("laura.vanoli@uniparthenope.it");
        email.add("bruno.volzone@uniparthenope.it");

    }


}
